---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: qrcode-generator
    tier: web
    env: prod
    kind: deployment
  name: qrcode-generator
  namespace: qrcode-generator-prod
spec:
  replicas: 2
  selector:
    matchLabels:
      app: qrcode-generator
#      tier: web
#      env: prod
  template:
    metadata:
      labels:
        app: qrcode-generator
        tier: web
        env: prod
        kind: pod
      namespace: qrcode-generator-prod
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
      containers:
      - image: registry.digitalocean.com/ameelio-registry/qrcode-generator:${RELEASE_VERSION}
        name: qrcode-generator
        imagePullPolicy: Always
        ports:
        - containerPort: 4000
          protocol: TCP
        readinessProbe:
          httpGet:
            path: /health_check/readiness
            port: 4000
          initialDelaySeconds: 5
          periodSeconds: 2
        envFrom:
          - configMapRef:
              name: qrcode-generator-web-config
          - secretRef:
              name: qrcode-generator-deploy-secrets
        securityContext:
          allowPrivilegeEscalation: false
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - qrcode-generator
                    - key: tier
                      operator: In
                      values:
                        - web
                topologyKey: doks.digitalocean.com/node-id

---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: qrcode-generator-pdb
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: qrcode-generator
#      tier: web
#      env: prod

---
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: qrcode-generator
    env: prod
    kind: configmap
  name: qrcode-generator-web-config
  namespace: qrcode-generator-prod
data:
  LOG_LEVEL: 'info'

# Service annotations for Digital Ocean
# https://docs.digitalocean.com/products/kubernetes/how-to/configure-load-balancers/

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: qrcode-generator
    tier: web
    env: prod
    kind: service
  name: qrcode-generator
  namespace: qrcode-generator-prod
  annotations:
    service.beta.kubernetes.io/do-loadbalancer-protocol: "http"
    service.beta.kubernetes.io/do-loadbalancer-size-slug: "lb-small" # or lb-medium|lb-large
spec:
  type: LoadBalancer
  selector:
    app: qrcode-generator
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 4000
      nodePort: 30000

---
apiVersion: domain-name-operator.tamx.org/v1
kind: CloudflareDnsRecord
metadata:
  name: qrcode-generator-prod
  labels:
    app: qrcode-generator
    tier: web
    env: prod
    kind: cloudflarednsrecord
  namespace: qrcode-generator-prod
spec:
  hostName: qrcode-generator-prod.ameelio.org
  serviceName: qrcode-generator
  proxied: true

---
apiVersion: domain-name-operator.tamx.org/v1
kind: CloudflareDnsRecord
metadata:
  name: accounts
  labels:
    app: qrcode-generator
    tier: web
    env: prod
    kind: cloudflarednsrecord
  namespace: qrcode-generator-prod
spec:
  hostName: qrcode.ameelio.org
  serviceName: qrcode-generator
  proxied: true
